name: evenvo_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.5
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.2.0
  qr_code_scanner: ^1.0.1
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  intl: ^0.20.2
  http: ^1.2.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
    - assets/logo.png
    - assets/female_avatar.png
    - assets/male_avatar.png
    - assets/LogoClient.png
    - assets/background_illustration.png

  fonts:
    - family: CenturyGothic
      fonts:
        - asset: assets/fonts/centurygothic.ttf
