services:
  - type: static_site
    name: evenvo-mobile-web-premium
    repo: https://github.com/EvSol28/Evenvo-Mobile-Web-Premium
    branch: main
    buildCommand: flutter build web --release --no-tree-shake-icons
    publishDir: build/web
    envVars:
      - key: FLUTTER_WEB
        value: true
      - key: FORCE_REBUILD
        value: "2026-01-01-15:40"